language: go
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
    - APP_DB_USERNAME=postgres
    - APP_DB_PASSWORD=
    - APP_DB_NAME=travis_ci_test
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "ap-south-1"
  app: "my-new-app"
  env: "Mynewapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-055596350215"
  on:
    branch: main