language: go
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  global:
    - APP_DB_USERNAME=postgres
    - APP_DB_PASSWORD=
    - APP_DB_NAME=travis_ci_test