version: '3'

services: 
    app:
        build: .
        environment: 
            "APP_DB_USERNAME": "postgres"
            "APP_DB_PASSWORD": "postgres"
            "ENV APP_DB_NAME": "postgres"
        ports: 
            - 8085:8085
        networks: 
            - custom-network
    
    db:
        image: postgres
        restart: always
        environment: 
            POSTGRES_PASSWORD: postgres
        networks: 
            - custom-network

networks: 
    custom-network:
        name: custom-network-1